### ISSUE TITLE
I'll create a complementary dApp market map you can use

### ISSUE THREAD

**Issue by youarentryan** [EthereumCommunityFund/ethereum-ecosystem-map#4]
Going to do a light version today and a more robust version over the course of the summer

**Comment by youarentryan** [comment]
WIP but sharing now:
https://github.com/ConsenSysLabs/dapp-ecosystem-map
@awasunyin @cassshih @cassandrashi

**Comment by youarentryan** [comment]
Want to link it in?

**Comment by awasunyin** [comment]
Hey I will look into it first

**Comment by youarentryan** [comment]
sounds good!

**Comment by awasunyin** [comment]
@youarentryan sorry for the delay!

I've checked this link: https://github.com/ConsenSysLabs/dapp-ecosystem-map and I love the joke on EOS, even though I know I should remain objective. 

Phrasing from the README.md: 
1. "_examples of relevant projects_", I would like to know what qualifies a project in the dApp world as "relevant", would you find it acceptable to write a definition or description of what you look at and consider before you tag a project as relevant?
- Initially I wanted to do this dApp mapping, but I found some challenges:
I. There are a lot of projects public but very few actually active on chain (measured by transactions or deployed and called smart contracts)
II. Related to (I), Etherscan is not the best to navigate, find and rank _active_ projects on Ethereum, I've checked https://dappinsight.com which is a great data-driven source, but I was extremely underwhelmed by the number of projects who are _actually_ active. 
III. Another downside of https://dappinsight.com is that they are advertising for certain projects, which sometimes makes me question the reliability of the projects announced. 
IV. Considering all this, when I started to write the dApp mapping, _rellevance_ was defined by the project being novel: either they were tackling a new industry, product, together mixed with _active on ethereum_. 
V. The main downside of this is that, as I write only 1 project and in most cases there are many competing projects, I would be extremely biased and write only a _well-known_ one. 

I've checked your categorization. It's an interesting perspective. Because taxonomies are very complex and there's no single solution, especially in this ever-rapidly-changing industry and full of noise, I would just like to share my view on dApps categorization. 

Please bare in mind that I'm not trying to persuade you into this is a _better_ one anyhow, I just want to share in case it can be useful for you:
![dapps_taxonomy](https://user-images.githubusercontent.com/11296013/41494828-c23fd93c-70ce-11e8-80ad-d6504708c346.png)
*Note:  I've not worked on this for a while, might be slightly deprecated or just unfinished. 

Noted on:
```
Notes:
Themes are neither mutually exclusive or collectively exhaustive
Trustless exchange, decentralization, state mutation, and tokenization span each theme
Projects can be industry-specific or generally applicable
Examples focus on Ethereum-based projects
```
Which I totally agree with. I just wanted to point out examples on how projects such as `aragon` can also belong to the dApp world (as Aragon in itself is a DAO) but at the same time show up in our infrastructure mapping, tagged as "application-specific protocol". It's well pointed out in your README.md notes, I just wanted to write it in my comments.

Anyways, if any of my feedback sounds offensive anyhow, please let me know. I tend to give very honest and direct feedback. Great initiative!  (☆▽☆)

**Comment by youarentryan** [comment]
Hey Awa, thank you for the feedback, and I agree with all of your points above. I'd like to create a more robust and scientific mapping once we have better transactional on chain data. And I think the map you've pulled together has a clearer ontological objectivity. The one I created was meant to be more of an interpretive framework to contextualize the usage themes behind blockchain technology. Absolutely no need to integrate with the mapping found here, as the one I've pulled together has a different audience and a different methodology. Appreciate you taking the time to respond, and I look forward to continuing the conversation!
